# Generated by Django 6.0.1 on 2026-02-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=30, unique=True)),
                ('category_desc', models.CharField(max_length=256)),
            ],
        ),
    ]
