# Generated by Django 6.0.1 on 2026-02-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_department_profile_active_status_profile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_desc',
            field=models.CharField(max_length=256),
        ),
    ]
