# Generated by Django 5.1.6 on 2026-03-08 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_user_address_user_apartment_user_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='street_address',
            new_name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='apartment',
        ),
    ]
