# Generated by Django 6.0.1 on 2026-04-04 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_api_tables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
