# Generated by Django 5.1.6 on 2026-03-14 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IdeaPost', '0002_initial'),
        ('interaction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('SWEARING', 'Swearing'), ('LIBEL', 'Libel'), ('SPAM', 'Spam'), ('HARASSMENT', 'Harassment'), ('OTHER', 'Other')], max_length=20)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='IdeaPost.idea')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idea_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('reporter', 'idea', 'reason')},
            },
        ),
    ]
