# Generated by Django 5.1.6 on 2026-03-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClosurePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('idea_closure_date', models.DateField()),
                ('comment_closure_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.CharField(max_length=20)),
            ],
        ),
    ]
