# Generated by Django 6.0.2 on 2026-02-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closure_period', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='closureperiod',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
