# Generated by Django 5.1.6 on 2026-03-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closure_period', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closureperiod',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
