# Generated by Django 6.0.2 on 2026-02-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closure_period', '0002_closureperiod_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closureperiod',
            name='academic_year',
            field=models.CharField(max_length=20),
        ),
    ]
