# Generated by Django 6.0.2 on 2026-02-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closure_period', '0003_alter_closureperiod_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closureperiod',
            name='comment_closure_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='closureperiod',
            name='idea_closure_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='closureperiod',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
