# Generated by Django 5.1.6 on 2026-03-07 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('closure_period', '0002_alter_closureperiod_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('idea_id', models.AutoField(primary_key=True, serialize=False)),
                ('idea_title', models.CharField(max_length=50)),
                ('idea_content', models.TextField()),
                ('anonymous_status', models.BooleanField(default=False)),
                ('submit_datetime', models.DateTimeField(auto_now_add=True)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(related_name='ideas', to='api.category')),
                ('closurePeriod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='closure_period.closureperiod')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='idea_documents/')),
                ('file_name', models.CharField(max_length=50)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='IdeaPost.idea')),
            ],
        ),
    ]
