# Generated by Django 6.0.2 on 2026-03-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('idea_id', models.AutoField(primary_key=True, serialize=False)),
                ('idea_title', models.CharField(max_length=50)),
                ('idea_content', models.TextField()),
                ('anonymous_status', models.BooleanField(default=False)),
                ('submit_datetime', models.DateTimeField(auto_now_add=True)),
                ('terms_accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='idea_documents/')),
                ('file_name', models.CharField(max_length=50)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
