# Generated by Django 6.0.2 on 2026-03-12 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('IdeaPost', '0001_initial'),
        ('api', '0001_initial'),
        ('closure_period', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='categories',
            field=models.ManyToManyField(db_table='Idea_Category', related_name='ideas', to='api.category'),
        ),
        migrations.AddField(
            model_name='idea',
            name='closurePeriod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='closure_period.closureperiod'),
        ),
        migrations.AddField(
            model_name='idea',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department'),
        ),
        migrations.AddField(
            model_name='idea',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='IdeaPost.idea'),
        ),
    ]
