# Generated by Django 5.1.6 on 2026-03-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IdeaPost', '0001_initial'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE "IdeaPost_idea_categories" RENAME TO "Idea_Category";',
                    reverse_sql='ALTER TABLE "Idea_Category" RENAME TO "IdeaPost_idea_categories";',
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='idea',
                    name='categories',
                    field=models.ManyToManyField(db_table='Idea_Category', related_name='ideas', to='api.category'),
                ),
            ],
        ),
    ]
