# Generated by Django 5.1.6 on 2026-03-07 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IdeaPost', '0002_ideacategory_and_categories_through'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                'ALTER TABLE "Idea_Category" DROP CONSTRAINT "IdeaPost_idea_categories_pkey";',
                'ALTER TABLE "Idea_Category" DROP COLUMN "id";',
                'ALTER TABLE "Idea_Category" ADD CONSTRAINT "Idea_Category_pkey" PRIMARY KEY ("idea_id", "category_id");',
            ],
            reverse_sql=[
                'ALTER TABLE "Idea_Category" DROP CONSTRAINT "Idea_Category_pkey";',
                'ALTER TABLE "Idea_Category" ADD COLUMN "id" BIGINT GENERATED BY DEFAULT AS IDENTITY;',
                'ALTER TABLE "Idea_Category" ADD CONSTRAINT "IdeaPost_idea_categories_pkey" PRIMARY KEY ("id");',
            ],
        ),
    ]
