# Generated by Django 6.0.1 on 2026-03-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IdeaPost', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddocument',
            name='file_name',
            field=models.TextField(),
        ),
    ]
