# Generated by Django 5.1.6 on 2026-03-07 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('activity_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, default='page_view', max_length=50)),
                ('path', models.CharField(db_index=True, max_length=255)),
                ('browser', models.CharField(blank=True, default='', max_length=100)),
                ('operating_system', models.CharField(blank=True, default='', max_length=100)),
                ('device_type', models.CharField(blank=True, default='', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at', 'event_type'], name='analytics_a_created_965e04_idx'), models.Index(fields=['user', 'created_at'], name='analytics_a_user_id_1fe5d2_idx'), models.Index(fields=['path', 'created_at'], name='analytics_a_path_168f6b_idx')],
            },
        ),
    ]
