# Generated by Django 6.0.1 on 2026-04-04 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_rename_activitylog_table'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='ActivityLog_created_2f5aa3_idx',
            old_name='analytics_a_created_965e04_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='ActivityLog_user_id_427db1_idx',
            old_name='analytics_a_user_id_1fe5d2_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='ActivityLog_path_38f221_idx',
            old_name='analytics_a_path_168f6b_idx',
        ),
    ]
